name: React App Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Update to latest version (v3)

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Update to latest version (v3)
        with:
          node-version: '20'  # Use Node.js 20

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
