name: React App Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Update to the latest major version (v4)

      - name: Set up Node.js
        uses: actions/setup-node@v4  # Update to the latest major version (v4)
        with:
          node-version: '16'  # Use Node.js 16 (or higher)

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
